export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const SET_CHALLENGED_USER = 'SET_CHALLENGED_USER';
export const SET_CURRENT_CHALLENGE = 'SET_CURRENT_CHALLENGE';
export const SET_CURRENT_CATEGORY = 'SET_CURRENT_CATEGORY';
export const SET_POLL_TIMER = 'SET_POLL_TIMER';